/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_meridiana;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author JHPAT<sanhool@live.com.mx>
 */
public class Menu extends javax.swing.JFrame {

    //inicialiso variables de la lista
    public static DefaultListModel lista_p = new DefaultListModel();
    /**
     * Creates new form Menu
     */
    public static int suma = 0;
  
    public static void total_suma(int valor, int tipo){
        
      suma = suma + valor;
      
         String s = Integer.toString(suma);
        
     }
    public void resta(){
        String texto="MEDIANA";
        texto.indexOf(texto);
    }
    
    
    public Menu() {
        initComponents();
        
        pizzas ventana_2 = new pizzas();
     ventana_2.setVisible(true);  
    
     
        // inicialiso los componenetes de la lista 
      lista_p = new DefaultListModel();
      
      lista_pedido.setModel(lista_p);
      
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lista_pedido = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        carrito_a = new javax.swing.JButton();
        eleminar_seleccion_b = new javax.swing.JButton();
        Eliminar_pedido_b = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccion_texto = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        total_txt = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 570));
        setMinimumSize(new java.awt.Dimension(800, 570));
        getContentPane().setLayout(null);

        jScrollPane2.setViewportView(lista_pedido);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 150, 200, 200);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_1.png"))); // NOI18N

        carrito_a.setBackground(new java.awt.Color(255, 255, 255));
        carrito_a.setForeground(new java.awt.Color(255, 255, 255));
        carrito_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_orden.png"))); // NOI18N
        carrito_a.setBorder(null);
        carrito_a.setBorderPainted(false);
        carrito_a.setContentAreaFilled(false);
        carrito_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrito_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 590, Short.MAX_VALUE)
                .addComponent(carrito_a, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(carrito_a)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 80);

        eleminar_seleccion_b.setBackground(new java.awt.Color(255, 0, 0));
        eleminar_seleccion_b.setForeground(new java.awt.Color(255, 255, 255));
        eleminar_seleccion_b.setText("Eliminar Seleccion");
        eleminar_seleccion_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleminar_seleccion_bActionPerformed(evt);
            }
        });
        getContentPane().add(eleminar_seleccion_b);
        eleminar_seleccion_b.setBounds(250, 380, 140, 32);

        Eliminar_pedido_b.setBackground(new java.awt.Color(255, 0, 0));
        Eliminar_pedido_b.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_pedido_b.setText("Eiminar Pedido");
        Eliminar_pedido_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_pedido_bActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_pedido_b);
        Eliminar_pedido_b.setBounds(400, 380, 140, 32);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setMaximumSize(new java.awt.Dimension(170, 28));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Resumen del la orden");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(320, 110, 170, 28);

        direccion_texto.setColumns(20);
        direccion_texto.setRows(5);
        jScrollPane1.setViewportView(direccion_texto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 190, 223, 83);

        jToggleButton1.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton1.setText("Agregar Direccion");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(570, 300, 140, 32);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setMaximumSize(new java.awt.Dimension(170, 28));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Direccion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(560, 150, 170, 28);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        total_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(total_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(310, 430, 200, 70);

        jToggleButton2.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton2.setText("Calcular");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(550, 450, 140, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Primer_Fondo_Menu.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -440, 1180, 980);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carrito_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrito_aActionPerformed
 
    }//GEN-LAST:event_carrito_aActionPerformed

    private void eleminar_seleccion_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eleminar_seleccion_bActionPerformed
        // elimino seleccion de la lista
        int eliminar = lista_pedido.getSelectedIndex();
       

        String texto=lista_pedido.getSelectedValue();
          
        if ( texto.indexOf("MEDIANA") != -1 && texto.indexOf("CAMARONES" ) != -1 ){
            suma = suma - 200;
        }else  if ( texto.indexOf("GRANDE") != -1 && texto.indexOf("CAMARONES" ) != -1 ){
            suma = suma - 280;
        }else  if ( texto.indexOf("MEDIANA") != -1 ){
            suma = suma - 150;
        }else  if ( texto.indexOf("GRANDE") != -1 ){
            suma = suma - 210;
        }
        String s = Integer.toString(suma);
        total_txt.setText("$ "+ s);
         lista_p.remove(eliminar);
    }//GEN-LAST:event_eleminar_seleccion_bActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // Obtengo el texto de la direccion 
     
      String direccion =  direccion_texto.getText();
      
      //Mando a la lista 
      lista_p.addElement(direccion);
      
      direccion_texto.setText("");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void Eliminar_pedido_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_pedido_bActionPerformed
        // elimino todo de la lista 
         int eliminar_todo = lista_pedido.getSelectedIndex();
        lista_p.removeAllElements();
         suma = 0;
        String s = Integer.toString(suma);
        total_txt.setText("$" + s);
    }//GEN-LAST:event_Eliminar_pedido_bActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
      String s = Integer.toString(suma);
        total_txt.setText("$" + s);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar_pedido_b;
    private javax.swing.JButton carrito_a;
    private javax.swing.JTextArea direccion_texto;
    private javax.swing.JButton eleminar_seleccion_b;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public javax.swing.JList<String> lista_pedido;
    public javax.swing.JLabel total_txt;
    // End of variables declaration//GEN-END:variables
}
